### ISSUE TITLE
Youtube DL

### ISSUE THREAD

**Issue by jetgogoing** [azuse/youtube-streaming-translator-python#8]
一直遇到这个问题，尝试了好多办法都无法解决。我应该怎么处理？
Connecting to youtube...                             
Traceback (most recent call last):
  File "E:\youtube-streaming-translator-python-master\main.google.py", line 449, in <module>
    video = pafy.new(url)
  File "E:\youtube-streaming-translator-python-master\venv\lib\site-packages\pafy\pafy.py", line 124, in new
    return Pafy(url, basic, gdata, size, callback, ydl_opts=ydl_opts)
  File "E:\youtube-streaming-translator-python-master\venv\lib\site-packages\pafy\backend_youtube_dl.py", line 31, in __init__
    super(YtdlPafy, self).__init__(*args, **kwargs)
  File "E:\youtube-streaming-translator-python-master\venv\lib\site-packages\pafy\backend_shared.py", line 97, in __init__
    self._fetch_basic()
  File "E:\youtube-streaming-translator-python-master\venv\lib\site-packages\pafy\backend_youtube_dl.py", line 53, in _fetch_basic
    self._likes = self._ydl_info['like_count']
KeyError: 'like_count'

**Comment by azuse** [comment]
用的pafy这个工具太老了，可能youtube接口变了，已经无法再使用了
